name: Deploy to VPS

on:
  push:
    branches:
      - main
      - dev
      - 37-store-gossip-messages-for-fast-retrieval-of-edge-set

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_PRIVATE_KEY }}
          port: 22
          script: |
            cd ~/docker/gossip-syncer
            git checkout ${{ github.ref_name }}
            git pull origin ${{ github.ref_name }}
            docker-compose down
            docker-compose up -d --build